### ISSUE TITLE
Child process environment is not extended from process.env 

### ISSUE THREAD

**Issue by vibl** [sindresorhus/execa#101]
Child process environment is not extended from process.env.

On line 19 : `if (opts && opts.env && opts.extendEnv !== false)` evaluates to `false` because `opts.env` is undefined.

**Comment by sindresorhus** [comment]
// @SamVerschueren

**Comment by SamVerschueren** [comment]
@vibl did you actually experienced that? I agree that the `if` check evaluates to `false` when no default `env` is provided. But because of [this line](https://github.com/sindresorhus/execa/blob/master/index.js#L49), if you didn't set `preferLocal` explicitely to `false`, it should've still extended from `process.env`. 

I agree, the behaviour is shady and am doing a PR to actually solve this.

**Comment by vibl** [comment]
@SamVerschueren, yes, I did experienced that :-) I did some debugging and opt.env wasn't set. It should work now with your fix. Thanks!
