### ISSUE TITLE
When killing a process, ensure it was killed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#105]
When a user does `child.kill()` (NOT when `child.kill('SIGKILL')`), after some timeout (How long?), we should check if the process was actually killed with `process.kill(0)` and do `process.kill('SIGKILL')` if not.

**Comment by Ncf16** [comment]
Hello,

I am trying to fix this issue, my idea was to alter the handler removeExitHandler 
```javascript
// The handler in question
removeExitHandler = onExit(() => {
       // Added instruction
	setCheckKilled(spawned);
	spawned.kill();
	});

function setCheckKilled(spawned) {
		setTimeout(() => {
			checkDeath(spawned.pid, spawned.ppid, spawned.uid);
		}, TIME_TO_CHECK_KILL);

	}

function checkDeath(pid, ppid, uid) {
		console.log(pid + " " + ppid + " " + uid)
		findProcess.find("pid", pid).then((list) => compareFields({
			"ppid": ppid,
			"uid": uid
		}, list));
	}

```
I was thinking of using the package [find-process](https://www.npmjs.com/package/find-process). So that I could get the information related to the process to compare to what I have stored. However I have come across a problem, with the information returned by the find-process package I do no have access to the process itself. That lead me to have a better look at the issue and raised a question. 
In this context what is the difference between child and process?

**Comment by sindresorhus** [comment]
> I was thinking of using the package find-process.

That package is way too bloated and not even needed for this purpose.

> I do no have access to the process itself

I don't understand what you're trying to do.

> In this context what is the difference between child and process?

https://www.google.co.th/search?q="child+process"+vs+process

**Comment by sindresorhus** [comment]
I have already explained the solution in the issue text:

> we should check if the process was actually killed with process.kill(0) and do process.kill('SIGKILL') if not.
