### ISSUE TITLE
Not able to inject environment variables

### ISSUE THREAD

**Issue by sahibjotsaggu** [sindresorhus/execa#1093]
Couldn't find anything in the documentation but after learning that something like 

```javascript
execa`MY_ENV=testing echo $MY_ENV`
```

won't work, I saw that we can use the Options argument to define environment variables.

However, trying the following did not work as expected:

```javascript
const { stdout } = await execa({
  extendEnv: true,
  env: {
    $MY_ENV: "test",
  },
})`echo $MY_ENV`;
console.log(stdout); // $MY_ENV instead of test
```

Here's the [sandbox](https://codesandbox.io/p/devbox/gracious-wildflower-r2mzzv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwk2oqc900063b6l7hadnji5%2522%252C%2522sizes%2522%253A%255B59.473684210526315%252C40.526315789473685%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwk2oqc800023b6l5fpcco88%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwk2oqc900043b6lm9ag7ivk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwk2oqc900053b6l0fd3qra6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwk2oqc800023b6l5fpcco88%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwk2oqc800013b6lcweazosd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clwk2oqc800023b6l5fpcco88%2522%252C%2522activeTabId%2522%253A%2522clwk2oqc800013b6lcweazosd%2522%257D%252C%2522clwk2oqc900053b6l0fd3qra6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwk2oqc900053b6l0fd3qra6%2522%257D%252C%2522clwk2oqc900043b6lm9ag7ivk%2522%253A%257B%2522id%2522%253A%2522clwk2oqc900043b6lm9ag7ivk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwk2oqc900033b6l6h4pxgs0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwk2oqc900033b6l6h4pxgs0%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ehmicky** [comment]
Hi @sahibjotsaggu,

Thanks for reaching out. The answer to your question is in #1081 (and in the documentation links mentioned in that issue).

As a side note, please note that the environment variable names in the `env` option should not start with `$`. I.e. you want to do `env: {MY_ENV: "test"}`, not `env: {$MY_ENV: "test"}`.

**Comment by sahibjotsaggu** [comment]
Okay, I see from https://github.com/sindresorhus/execa/blob/main/docs/bash.md#environment-variables that environment variables should get injected but I'm getting this type error I can't seem to resolve:

<img width="227" alt="Screenshot 2024-05-24 at 12 23 27 PM" src="https://github.com/sindresorhus/execa/assets/8991960/4083199d-d871-41c4-a6cb-f74fa2636546">

```
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'env' does not exist in type 'URL'.ts(2769)
script.d.ts(22, 2): The last overload is declared here.
```

Any insight into this?

**Comment by ehmicky** [comment]
Hi @sahibjotsaggu,

To help solving those issues, I would recommend:
  - Creating different issues since this is different from the initial problem
  - Pasting the code instead of a screenshot, so we can copy-paste it
  - For types, including a fully reproducing example with https://www.typescriptlang.org/play
  - Include environment information: Node.js version, TypeScript version, TypeScript config

I have created the [following reproduction](https://www.typescriptlang.org/play/?ts=5.5.0-beta#code/JYWwDg9gTgLgBAbwCQF84DMoRHA5AUwA98BjAQ1wG4BYAKDrIHczh4kAKBOuHufAOwBuALkTdeEgCoBBAEoBxAKKSA+ooByANVG4wWACYBXEjGAR+ucTxR0UASgAG-MDiiH+cAEaHgAG30OlEA), and the above seems to work.

Is there anything in the TypeScript documentation's [troubleshooting section](https://github.com/sindresorhus/execa/blob/main/docs/typescript.md#troubleshooting) that's helping? In particular: the part about the minimum TypeScript version, and the part about ES modules.

**Comment by SebastienGllmt** [comment]
@sahibjotsaggu I found the cause and fix for your issue

if the values in the your `env` object are not strings, you will get this error. This is because the `env` option is defined as follows:

```ts
readonly env?: Readonly<Partial<Record<string, string>>>
```

That means that:
1. ✖ `env: { FORCE_COLOR: true }` ← this is a compiler error (with the `'env' does not exist in type 'URL'` error)
2. ✅ `env: { FORCE_COLOR: "true" }` ← this will work
