### ISSUE TITLE
Memory Leak of pipe

### ISSUE THREAD

**Issue by guoh27** [sindresorhus/execa#1134]
```js
const tarFile = "test.tgz"
const pv = execa('pv', {
                stdout: { file: tarFile },
            })
await execa('tar', ['-czf', '-', '-C', '.']).pipe(pv)
```
if tar a big tarball, memory will increse to max and make system stuck

**Comment by guoh27** [comment]
```js
const tarFile = "test.tgz"
const pv = execa('pv', {
    stdout: { file: tarFile },
    stderr: 'ignore'
})
await execa('tar', ['-czf', '-', '-C', '.'], {
    buffer: false
}).pipe(pv)
```

buffer: false not work

**Comment by ehmicky** [comment]
Hi @guoh27,

By default, Execa allows you to retrieve the result of both commands: `tar` and `pv` (piped with `tar`). You can retrieve that result using `result.stdout`, `result.stderr`. For `pv`, you can retrieve both commands [using `result.pipedFrom[0]`](https://github.com/sindresorhus/execa/blob/main/docs/pipe.md#result). This can prove very useful for debugging, among other things. To do this, the result must be buffered, which takes memory.

The [`buffer: false` option](https://github.com/sindresorhus/execa/blob/main/docs/output.md#low-memory) opts out of this, in order to lower memory consumption. Since both commands' results can be retrieved, you need to use `buffer: false` on both commands in your case.

```js
const tarFile = "test.tgz"
const pv = execa('pv', {
  stdout: { file: tarFile },
  buffer: false,
})
await execa('tar', ['-czf', '-', '-C', '.'], { buffer: false }).pipe(pv)
```

Note that you can also use the following shortcut notation:

```js
const tarFile = "test.tgz"
await execa('tar', ['-czf', '-', '-C', '.'], { buffer: false })
  .pipe('pv', { stdout: { file: tarFile }, buffer: false })
```

Or the template string syntax:

```js
const tarFile = "test.tgz"
await execa({buffer: false})`tar -czf - -C .`
  .pipe({ stdout: { file: tarFile }, buffer: false })`pv`
```

**Comment by guoh27** [comment]
Thank you very much for your detailed answer, it worked
