### ISSUE TITLE
Timeout / cancel stuck process

### ISSUE THREAD

**Issue by zirkelc** [sindresorhus/execa#1137]
Hey,

sorry for asking a question as an issue, I thought it might be a useful feature if it doesn't already exist. Execa has options for [`timeout`](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#timeout) and [cancel signal](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#canceling). 

I had a few cases where a process running a Node.js script got stuck because of an error, but the script didn't properly throw this error so the process kept running but didn't print anything to sdtout/stderr.

In such cases it would be nice to have timeout that resets after each update on on sdtout/stderr,  so that you can distinguish a long running process from a stuck process.

**Comment by ehmicky** [comment]
Hi @zirkelc,

This is an interesting use case, but might be too specific to add as a built-in feature since it can be achieved by users with some additional code.

Instead, I would favor adding an example to the documentation, more specifically the [Timeout](https://github.com/sindresorhus/execa/blob/main/docs/termination.md#timeout) section. The following example will terminate the subprocess if it did not print on `stdout` in the last minute.

```js
import {execa} from 'execa';
import debounceFn from 'debounce-fn';

const controller = new AbortController();
const NO_OUTPUT_TIMEOUT = 60000;
const abort = debounceFn(controller.abort.bind(controller), {wait: NO_OUTPUT_TIMEOUT});

abort();
for await (const line of execa('npm', ['run', 'build'], {cancelSignal: controller.signal})) {
  abort();
}
```

@sindresorhus Do you think an example would be enough here? Also, what are your thoughts about this example?

**Comment by zirkelc** [comment]
Hi @ehmicky 

thanks for this example, I was expecting it was already somehow possible 😄

**Comment by sindresorhus** [comment]
The example looks good and it's the right solution here.

**Comment by zirkelc** [comment]
Thank you for the help!
