### ISSUE TITLE
Cannot continue after killing the execa process

### ISSUE THREAD

**Issue by un0tec** [sindresorhus/execa#1173]
Given the following code:

```js
const execaProcess = execa('aws', ['sso', 'login', '--profile', 'example', '--no-browser'], {
    stdout: 'pipe'
});

const url = await new Promise((resolve, reject) => {
    execaProcess.stdout.on('data', (data) => {
        const output = data.toString();
        const lines = output.split('\r\n');
        resolve(lines[lines.length - 2]?.trim());
    });
});

try {
    await fkill(execaProcess.pid, { force: true });
} catch (error) {
    console.log(error);
}

const browser = await puppeteer.launch({ headless: false, args: ['--lang=en'] });
```

After run `await fkill(execaProcess.pid, { force: true });` no more code can be executed, it is displayed:

`ExecaError: Command failed with exit code 1: aws sso login --profile example--no-browser`

I've also tried using `terminate` package, but I get the same error.

What is the correct way to end a command using streams? I need to use stream because executing that command is waiting for X actions or ending with CtrlC.

I'm on Windows, but I would need cross-platform. Thanks

**Comment by ehmicky** [comment]
Hi @un0tec,

This question has multiple parts to it. I'm going to skip the puppeteer part of your example since it seems unrelated.

The streaming logic has some issues. It relies on the assumption that the first chunk of `data` will be exactly the output you're expecting, with the second-to-last line being the line you're looking for. It is not impossible that `aws sso login` might split that output into several chunks of `data`, for example, if it is being slow. `resolve()` can only be called once, so it would get the wrong output.

Another thing is that the `url` promise will never resolve if `aws sso login` never has any output, e.g. if `aws` is not installed on the machine.

Also, `\r\n` is Windows specific, so not cross-platform.

The proper way to retrieve a specific output line in a streaming and cross-platform fashion would be to use async iteration. [See the full documentation here](https://github.com/sindresorhus/execa/blob/main/docs/lines.md).

```js
const subprocess = execa`aws sso login --profile example --no-browser`;
let url;
for await (const line of subprocess) {
  if (line.startsWith('Expected start of the line')) {
    url = line;
    subprocess.kill();
    break;
  }
}
```

The subprocess will fail, and that's normal. Terminating a subprocess is not graceful and results in a non-0 exit code. [See the documentation here](https://github.com/sindresorhus/execa/blob/main/docs/termination.md). Therefore, it rejects the `subprocess` promise. However, you can pass the [`reject: false`](https://github.com/sindresorhus/execa/blob/main/docs/errors.md#preventing-exceptions) option to prevent that.

**Comment by un0tec** [comment]
Hi @ehmicky 

Thank you for all the explanations, I was misinterpreting the documentation I had read.

I have been testing with all your indications. According to [documentation](https://github.com/sindresorhus/execa/blob/main/docs/lines.md), now my problem is that I cannot finish the process until I have completed a few steps. For example:

```
const subprocess = execa({reject: false})`aws sso login --profile example --no-browser`;
let url;
for await (const line of subprocess) {
  if (line.startsWith('Expected start of the line containing the URL')) {
    url = line;
    subprocess.kill();  --> I can't finish the process so soon
    break;
  }
}

[need to execute code]

[now I can kill the process]
```
Is the following code correct?

```
for await (const line of subprocess) {
  if (line.startsWith('Expected start of the line containing the URL')) {
    url = line;
    logicMethod(url)  --> new async method? (in order not to block the loop)
    subprocess.kill();
    break;
  }
}
```
or is there a better way?

Thanks in advance.

**Comment by ehmicky** [comment]
Yes, this is correct. You can use `await logicMethod(url)` if the operation is async.
