### ISSUE TITLE
`reject` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#13]
Currently `execa` rejects the promise on non-zero exit code. Sometimes though, you want to get the output regardless, like e.g. running ESLint and reading the result regardless of it having linter issues.

Not totally sold on the name. Suggestions welcome.

Does this option make sense?

**Comment by mbad0la** [comment]
Why can't we use the `catch` method upon rejection of our promises? That can be used to display results such as linter issues. Am I missing out on something?

**Comment by sindresorhus** [comment]
@mbad0la That works, but it's more verbose when using async functions as you need to wrap it in a try/catch. Example: https://github.com/sindresorhus/execa/blob/9345d2ccc030dde43282d111bf8196f3aaf3715f/test.js#L26-L30

**Comment by mbad0la** [comment]
@sindresorhus I get it and I do support this functionality. Are we having it as a parameter so that we can control this functionality?   
Btw, What do you think about the name `overrideReject`? Personally, the rejection is not an _error_ as we might get our desired behaviour through `catch` as I mentioned earlier. So having the word Error in the option is maybe not that correct. What do you think about this?

**Comment by sindresorhus** [comment]
> Are we having it as a parameter so that we can control this functionality?

Yes, read the issue title.

-

Maybe just `{reject: false}`.

**Comment by mbad0la** [comment]
My bad, sorry about the question. `reject` works with me.
