### ISSUE TITLE
Windows - execa assumes that the windows shell is always cmd

### ISSUE THREAD

**Issue by GuyBransgrove** [sindresorhus/execa#146]
Prompted by: https://github.com/cypress-io/cypress/issues/789

The handleShell function should account for windows environments not necessarily using cmd as their default shell.

**Comment by ramblinjan** [comment]
Additional information: this works from visual studio code's integrated terminal (specifically a non-login shell but instead an interactive shell), but not git bash (specifically a login shell).

Not sure how helpful this is as I'm not sure what other magic VSCode's terminal might do, but the distinction may help isolate a fix.

**Comment by n4bb12** [comment]
I'm using git bash on windows and this works for me:
```
execa.shell(`sh -c \"${bashCommand}\"`)
```

**Comment by sindresorhus** [comment]
> execa assumes that the windows shell is always cmd

The built-in `child_process` does this too. You can use the `shell` option with the [`default-shell`](https://github.com/sindresorhus/default-shell) module to work around this. It's out of scope of Execa to guess your default shell as that might lead to surprising behavior. Execa doesn't do this on macOS/Linux either.

**Comment by dwelle** [comment]
@sindresorhus even if we pass different `shell` to execa, it still forces the `/d /s /c` on windows (as per docs), which won't help. If we e.g. pass a `bash.exe` installed via [git-scm](http://git-scm.com) (I think they're using some msys/mingw bash), then we're out of luck, because that shell is more UNIX-y than it is Windows-like (and for good reason), and doesn't understand any `/d /s /c` switches (but understands `-c` switch).

**Comment by sindresorhus** [comment]
Yes, supporting cmd.exe-incompatible shells is not easy and not something I plan to support here.

**Comment by Tobbe** [comment]
For anyone coming here in the future, this has been fixed by https://github.com/sindresorhus/execa/pull/181
