### ISSUE TITLE
Make the child process closer to a real Promise

### ISSUE THREAD

**Issue by callumlocke** [sindresorhus/execa#147]
Execa doesn't implement `.finally()` on the child process. This is making it difficult to come up with a correct Flow type definition for it – see discussion [on this PR](https://github.com/flow-typed/flow-typed/pull/2585).

Would you object to adding a `.finally()` method to execa's spawned child process, to make it fully implement `Promise`?

The `.finally()` method is at Stage 4 and is in the latest [draft spec](https://tc39.github.io/ecma262/#sec-promise.prototype.finally).

**Comment by bradfordlemley** [comment]
Would it be possible (or desirable) to define execa as returning an enhanced Promise, rather than an enhanced child process?  I.e., extend Promise type like [bluebird's flowdef](https://github.com/flow-typed/flow-typed/blob/b37363e786e18db641ee1a66820d862e16297704/definitions/npm/bluebird_v3.x.x/flow_v0.70.x-/bluebird_v3.x.x.js#L53)?

There are several defs in flow-typed that extend Promise and that seems like the ideal pattern for Promise compatibility, if possible.

**Comment by sindresorhus** [comment]
Yes, that’s what I would type it as.
