### ISSUE TITLE
child promise always rejects because node only sets exitCode or signalCode not both.

### ISSUE THREAD

**Issue by krisselden** [sindresorhus/execa#150]
https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L218

As you can see, the exit handler of node only sets signalCode if there is a signalCode and not this.exitCode (which is initialized as null) and fires the event with this.signalCode and this.exitCode.

Node only treats < exitCode as  error: https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L231

But execa subscribes to exit and requires exitCode to === 0 or it fails.
https://github.com/sindresorhus/execa/blob/master/index.js#L277

Maybe the closePromise should subscribe to the 'close' event instead? https://github.com/nodejs/node/blob/master/lib/internal/child_process.js#L963

**Comment by sindresorhus** [comment]
It does indeed sound like the `close` event might be a better choice, although not entirely clear to me what the implications would be:

> The 'close' event is emitted when the stdio streams of a child process have been closed. This is distinct from the 'exit' event, since multiple processes might share the same stdio streams. - https://nodejs.org/api/child_process.html#child_process_event_close

According to https://stackoverflow.com/questions/37522010/difference-between-childprocess-close-exit-events, it seems using `close` will be fine.

Thoughts?

**Comment by sindresorhus** [comment]
@ehmicky Thoughts on this?

**Comment by ehmicky** [comment]
About whether the `close` or `exit` event should be used to resolve/reject the main promise, this seems to me we should follow the behavior of Node.js as it's what users might expect. I.e. does `child_process.spawnSync()` finishes on `close` or on `exit` event? I tried to look into the [source code](https://github.com/nodejs/node/blob/master/src/spawn_sync.cc) and it seemed to me it did on `exit` event, but I am not 100% sure. This also seems to make more sense to me, where a child process might return/resolve (`exit` event, `execa` promise resolution) even when of its file descriptors are still open because used by other processed (`close` event). Please let me know if I got this wrong.

About signals I think the vast majority of users are going to use `SIGTERM` or similar, i.e. expects that if a child process stopped because of a signal, the `execa` promise should be rejected. For the use case of graceful exits I see some possible solutions though:
  1) let child processes handle it. For example a child process might listen to `SIGUSR1` to perform a graceful shutdown then call `process.exit(0)`. This would result in `execa` not rejected the main promise. On the other hand some users might not have control over those child processes, as @stefanpenner points out with the Chrome example.
  2) add an option to whitelist signals that should be considered ok.

What do you think @sindresorhus?

**Comment by stefanpenner** [comment]
I'm obviously biased, but i prefer 1.0 ;)

**Comment by ehmicky** [comment]
@stefanpenner I've just edited my comment to add more ideas.

**Comment by sindresorhus** [comment]
@stefanpenner Any thoughts on https://github.com/sindresorhus/execa/issues/150#issuecomment-469816283?

**Comment by stefanpenner** [comment]
I believe, regardless of signal we should only reject when receiving a non-zero status code. When and why should we deviate?

**Comment by ehmicky** [comment]
Let's break this issue down into smaller points:
  1) Should `exit` or `close` event be used?
  2) Should `execa` resolve or reject: 
     a) when the exit code is not `0`?
     b) on `error` events?
     c) when a signal was sent?

For 1) I think we should keep `exit`.
For 2) I think we should reject on a) or b) or c).
This is for the reasons mentioned above. This is also the current behavior.

**Comment by sindresorhus** [comment]
1. 👍 
2. 👍 Yes, I would reject on `a`, `b`, and `c`.

Closing as this is just the existing behavior.
