### ISSUE TITLE
How to handle output of webpack-dev-server?

### ISSUE THREAD

**Issue by nshoes** [sindresorhus/execa#198]
I'm using `execa` with `listr` and I'm having issues showing the output of `webpack-dev-server`:

```js
  {
    title: 'Starting webpack server',
    task: async () => {
      await execa('webpack-dev-server', ['--config=webpack/development.js'])
    }
  }
```
What am I doing wrong?

**Comment by ehmicky** [comment]
Hi @nshoes, try:

```js
{
    title: 'Starting webpack server',
    task: async () => {
      await execa('webpack-dev-server', ['--config=webpack/development.js'], { stdio: 'inherit' })
    }
}
```

**Comment by nshoes** [comment]
Thanks for the fast reply! That works. Seems that when there is any output, `listr`'s task list gets repeated: 
<img width="655" alt="Screen Shot 2019-04-01 at 7 30 00 AM" src="https://user-images.githubusercontent.com/4118389/55335530-1486b480-5450-11e9-8eaf-b9504d00736e.png">

Is there anyway around that?

**Comment by ehmicky** [comment]
I don't think that's something specific to `execa`. It is probably something to do with either `taskr` or `webpack-dev-server`. 

For example if you put a `console.log()` before `execa()` you should see it only gets called once. And it's most likely it does not repeat logs on its own. 

One common source of repeated logs I've found in my personal experience are because of spinners. Spinners sometimes repeat logs for a reason I ignore. But this is very likely not to be related to `execa`.

**Comment by nshoes** [comment]
Cool. Thanks for your help, I really appreciate it!
