### ISSUE TITLE
[Feature Request] Ignore undefined arguments

### ISSUE THREAD

**Issue by ozum** [sindresorhus/execa#315]
Hi,

Thanks for this module again.

```js
const typeFlag = type ? `--${type}` : undefined;
execa.sync("yarn", ["add", packageName, typeFlag]);
```

Is it possible to ignore undefined arguments as if they don't exist? If there are lots of optional arguments, having many conditional `args.push()` results in very long code.

EDIT:

Currently;
1. It is impossible to use `undefined` in arguments with TypeScript: `Type '(string | undefined)[]' has no properties in common with type 'SyncOptions<null>'.`
1. With JavaScript, passing `undefined` causes error in some commands. For example, `yarn` fails with undefined.

Thanks and kind regards,

**Comment by ehmicky** [comment]
Hi @ozum,

Thanks for reaching out. You can do:

```
const typeFlag = type ? [`--${type}`] : [];
execa.sync("yarn", ["add", packageName, ...typeFlag])
```

**Comment by ozum** [comment]
@ehmicky, thanks for the tip. It definitely works for my example.

If there are some typed functions/code down the road deeply, turning them from `string` to `array`, this may give wrong signal about meaning of the variables/functions (array instead of string). In some cases, it may be impossible, if function is used in multiple places.

```ts
function aFlag(should: boolean): string | undefined {
  return should ? "--aflag" : undefined;
}

function bFlag(should: boolean): string | undefined {
  return should ? "--bflag" : undefined;
}

...
function A(x: boolean, y: boolean): void {
  execa.sync("yarn", ["add", packageName, aFlag(x), bFlag(y)]);
}

function B(x: boolean, y: boolean): void {
  const args = [packageName, aFlag(x), bFlag(y)].filter(arg => arg !== undefined);
  execa.sync("yarn", ["add", packageName, ...args]);
}
```

I prefer `function A` instead of `function B`. Also, I understand if this request is considered irrelevant or out of scope by authors. If not, please reconsider to add this feature.

Thanks again.

**Comment by ehmicky** [comment]
From a typing perspective:
  - a variadic argument should be used when the number of arguments is unknown
  - an array with optional elements should be used when whether the argument exists is unknown

Spawning a process definitely falls into the first case. You should rewrite your `aFlag` function to return an array instead. For example, let's say that tomorrow `--aflag` becomes `--aflag true|false`, then you'll have to modify the return type of that function to an array anyway. Because conceptually it is actually an array of arguments.

Also this is what [`child_process.spawn()`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) does, and even the underlying OS calls such as [`exec` on Unix](http://man7.org/linux/man-pages/man3/exec.3.html).

**Comment by ozum** [comment]
Thanks again @ehmicky for your attention and the answer.
