### ISSUE TITLE
Hunt down weird Windows bug.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/execa#35]
See https://github.com/sindresorhus/execa/pull/27#issuecomment-215011451, and subsequent comments.

@kevva - If you could post a reproduction that proves this is a Node bug, we can file an issue in that repo and close this.

**Comment by kevva** [comment]
@jamestalmage, I'm not too sure I was correct. Testing it further I got `ENOENT` no matter the exit code.

**Comment by Glavin001** [comment]
My teammates running Windows are also experiencing the `spawn undefined ENOENT` error. Any workarounds? I personally use Mac and do not have an issue, however 3 different people on Windows are unable to run.

**Comment by SamVerschueren** [comment]
I came across this one when I was doing some development for `np`. So I started digging and took my Windows machine (ugh). The thing is, I couldn't reproduce the `spawn undefined ENOENT` with `childProcess.spawn`.

```js
const cp = childProcess.spawn('cmd', ['/c' 'yarn', 'check', '--integrity']);

cp.on('error', code => {
    console.log(code);
});

cp.on('exit', (code, signal) => {
    console.log('Exit', code, signal);
});
```

It exits with `Exit 1 undefined`, meaning in `execa`, this would result in [another error code](https://github.com/sindresorhus/execa/blob/master/index.js#L208-L209) then we always get, the `spawn undefined ENOENT`.

After starting to copy-paste quite a lot of code from `execa` and still not getting the same result, I noticed something weird. If you check the stack trace of the `spawn undefined ENOENT` error, you will notice that it comes from `cross-spawn/lib/enoent.js`. Interesting! So I started to look into `cross-spawn` and at line 45, we have [this check](https://github.com/IndigoUnited/node-cross-spawn/blob/master/lib/enoent.js#L45-L47).

```js
function verifyENOENT(status, parsed) {
    if (isWin && status === 1 && !parsed.file) {
        return notFoundError(parsed.original, 'spawn');
    }

    return null;
}
```

And that one seems to be the culprit. In my case, `status` is `1` but `parsed.file` is not present, `parsed.original` is neither so that's where the `spawn undefined ENOENT` comes from. So I removed [this line](https://github.com/sindresorhus/execa/blob/master/index.js#L243) in execa and suddenly I get what I expect.

> Command failed: cmd /c yarn check --integrity

With a status code of 1.

-------------------------
So I looked a little bit further, I mean, it shouldn't do that, then why is he doing that? It's definitely because we don't have `file` in our `parsed` options. So where does that come from in `execa`?

We have a [`handleArgs`](https://github.com/sindresorhus/execa/blob/master/index.js#L15) method that does the parsing right [here](https://github.com/sindresorhus/execa/blob/master/index.js#L18-L29). On my Windows machine, it used the `crossSpawn._parse` method which results in the following object.

```js
{
    command: 'cmd',
    args: ['/c', 'yarn', 'check', '--integrity'],
    options: {},
    file: 'C:\\WINDOWS\\system32\\cmd.EXE',
    original: 'cmd'
}
```

So here we have it, we have a `parsed.file` and `parsed.original` property. Then why is `crossSpawn._enoent` failing? If we look down at the bottom of `handleArgs`, we can see that we are not passing the `parsed` object back, but some custom `parsed` object, nothing `crossSpawn` would expect. So instead of passing the object like the one here into `crossSpawn._enoent`, we are passing some custom object to it that it doesn't recognize and BOOM!

So I altered the code a bit and made `handleArgs` return this object instead

```js
return {
	cmd: parsed.command,
	args: parsed.args,
	opts,
        parsed
};
```

And then right [here](https://github.com/sindresorhus/execa/blob/master/index.js#L243), I changed that line to 

```js
crossSpawn._enoent.hookChildProcess(spawned, parsed.parsed);
```

And 🎉, I got the error that I want!!!!!!

Will do a PR right now so please give me feedback on this. I might be missing some things as I'm not really familiar with the codebase.

**Comment by sindresorhus** [comment]
Woot! Super good find @SamVerschueren.

![5fa79994-b5ee-11e3-9a4d-b19557d7480b](https://cloud.githubusercontent.com/assets/170270/24089725/496c3a12-0d6c-11e7-9257-4ae8eb290be4.gif)

**Comment by SamVerschueren** [comment]
Hahaha, thanks :).
