### ISSUE TITLE
docs: state when the promise returned by execa will be rejected

### ISSUE THREAD

**Issue by yxliang01** [sindresorhus/execa#361]
There's no clear statement describing the situation when the promise returned by `execa` will be rejected. I currently assume it's same as the nodejs's built-in `child_process.spawn`, confirmation needed.

Thanks

**Comment by ehmicky** [comment]
Hi @yxliang01,

The promise is rejected in the same circumstances as `child_process.spawn()`, i.e.:
  - input validation
  - the exit code is not `0`
  - a terminal signal was sent to the child process
  - there was an internal/OS/lower-level problem creating the child process. For example when launching too many child processes at once.

Additionally the child process might time out or be cancelled, which are additional features provided by Execa.

Based on this I am not sure the documentation should state it. I would be happy to accept a PR if you thought otherwise though.

**Comment by ehmicky** [comment]
Implemented in #364.

**Comment by yxliang01** [comment]
:+1:
