### ISSUE TITLE
feat: handle EAGAIN

### ISSUE THREAD

**Issue by yxliang01** [sindresorhus/execa#362]
Sometimes, process creation can fail due to various external reasons. e.g. when `fork` is temporarily unavailable, error code of `EAGAIN` will be issued. I think would be great if execa has an extra option for setting number of trials when hitting `EAGAIN` error.

Thanks

**Comment by ehmicky** [comment]
Hi @yxliang01,

Can you list some examples where process creation temporarily fail, but might work when being retried later? 

The only thing I can think of are when there's not enough memory or when there are already too many processes. In those circumstances, I agree retrying on `EAGAIN` seems like the right thing to do. 

I am not sure though whether this should be implemented:
  - outside of execa: for example with a library dedicated to retrying a function on `EAGAIN` errors. This would be more modular and allow re-using this logic for other use cases.
  - inside execa. Since `EAGAIN` is one of the [errors of `fork()`](http://man7.org/linux/man-pages/man2/fork.2.html#ERRORS), this could be considered falling within the realm of process creation libraries.

What's your thought @sindresorhus?

**Comment by yxliang01** [comment]
@ehmicky Exactly and I'm indeed hitting this problem when the concurrency is not handled well. I think `EAGAIN` error is pretty suitable for being implemented inside `execa` because this problem is related to all cases of process creation and possible to occur any time anywhere (i.e. not specific to any particular use case of `execa`).

**Comment by sindresorhus** [comment]
I'm leaning towards including it in `execa`, as long as it doesn't cause too much complexity to the codebase. How many times should it retry? How long should it wait between each retry?

**Comment by yxliang01** [comment]
@sindresorhus Make them parameters. When undefined, disable retrials. How's that? Because there's no common values for these? But, I guess we will simply make a guess anyways. If unfit, change until okay.

**Comment by sindresorhus** [comment]
I don't like solutions like "just add some options". I prefer things to *just work*. Adding options should be the last effort, and if that's required, maybe it's not a good fit to have it in `execa`. I think we should start by thinking how we can make it *just work* in `execa` with defaults that will work for most.

**Comment by yxliang01** [comment]
Then, I would suggest try three times, interval of 1 second. (sounds standard?) In this way, fatal failure won't need to wait for too long before coming while normal temporary failure is addressed. I can't really justify what a commonly good value is, anyways. :)

**Comment by ehmicky** [comment]
I agree with @sindresorhus. I don't think most users will need those options.

**Comment by PeledYuval** [comment]
Hi,

Retry mechanisms should always use exponential backoff like the one implemented in [retry](https://www.npmjs.com/package/retry) or its extension [promise-retry](https://www.npmjs.com/package/promise-retry). Not using exponential backoff can easily worsen a problem by adding simultaneous retries to an already backlogged system.

In execa's case I *would not* add automatic retries to creating processes as receiving an error such as `EAGAIN` since they could be caused by an underlying, more serious, problem in the user's program architecture.

Since getting an error such as `EAGAIN` is not caused by an internal execa implementation but by the way a user uses execa, I would leave it up to the user to implement retries. Any user can add a retry mechanism if they need it.

**Comment by ehmicky** [comment]
I agree with @PeledYuval both for the exponential backoff and the fact that this feature should be done by the user not by Execa.

**Comment by sindresorhus** [comment]
We could at least document how to do it in the readme under a Tips section or something.

**Comment by yxliang01** [comment]
@sindresorhus Hmm sounds bit weird. If we document potentially frequently occurring code, why don't we provide it so that we can make it reused easily?
