### ISSUE TITLE
Question on stdin and stderr

### ISSUE THREAD

**Issue by TrevTheDev** [sindresorhus/execa#402]
Node doesn't return stdin and stderr data sequentially - unlike the terminal.  So stdin data may be returned before previous stderr data.  I've looked at your code to see how you handle that - but it seems that your code doesn't account for that?

One workaround is to force all data into either stdin or stderr as this forces sequential return.

**Comment by ehmicky** [comment]
Hi @TrevTheDev,

Do you mean `stdout` and `stderr`? My answer below assumes that you meant `stdout` instead of `stdin`.

I am not sure I understand what you mean. In any process, `stdout` and `stderr` are separate. In some processes such as terminals, they point to the same file (for example the terminal), leading them to be interleaved in a single stream. 

Execa inherits most of its behavior related to `stdin`, `stdout` and `stderr` to core Node.js `child_process`. We also offer an `all` option for merging `stdout` and `stderr` into a single stream.

**Comment by ehmicky** [comment]
Closing as stale.
