### ISSUE TITLE
git log - stdout and stderr empty

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/execa#406]
I've spent about 20 minutes searching the issues and couldn't find a similar one, so please forgive me if there's a duplicate out there. I'm trying to run a somewhat complex command with `git log`:

```js
const params = ['log', '--grep' , '"(pluginutils)"', 'pluginutils-v3.0.1..HEAD
'];
const result = await execa('git', params);
```

And the result of that command:

```js
{
  command: 'git log --grep "(pluginutils)" pluginutils-v3.0.1..HEAD',
  exitCode: 0,
  exitCodeName: 'SUCCESS',
  stdout: '',
  stderr: '',
  all: '',
  failed: false,
  timedOut: false
  isCanceled: false,
  killed: false
}
```

_(I've also tried prepending `--no-pager` to the params, but there was no change)_

Running that command in the terminal returns several commits. When I remove the `--grep` flag and value, `stdout` is then populated with a list of commits. Something about that `--grep` flag is squirrely. Any ideas?

**Comment by ehmicky** [comment]
Hi @shellscape,

I believe there might be some issue with the double quoting `"`.

When you run commands in a terminal, the command is first interpreted by Bash, which includes removing quoting. By default, Execa directly run commands at the OS-level without using any shell (unless the `shell: true` option is used, which is generally a bad idea). So you get the same result as if you were escaping the `"` in a terminal.

Removing the `"` might solve this. Please let me know if this solves your problem.

**Comment by shellscape** [comment]
That did it. FWIW on the command line that will fail without the quotes. I wonder, is there any kind of a mechanism that would make sense, which would warn a user about the possibility of quotes? Might be too abstract.

**Comment by ehmicky** [comment]
One issue with quoting is that it's shell specific. For example Windows users might use `cmd.exe` or Powershell. In your case, if you were on Windows, this would be hard to determine which shell you intended to use (since you are not using any shell actually in that case).

Also finding out if a quoting character was meant for quoting in the shell or for direct use by the command line tool seems like a very hard problem to solve IMHO. For example, in your case, you might actually intend to `grep` those double quotes (or not) depending on your intent, which might be hard to determine.

**Comment by shellscape** [comment]
Good info, thanks for the explanation.
