### ISSUE TITLE
[Help] Command Failing Only When using execa 

### ISSUE THREAD

**Issue by williamluke4** [sindresorhus/execa#416]
**Command**: `heroku pg:backups:download -a ${HEROKU_APP_NAME}`

I've been trying to debug why this is happening but the output does not tell me very much. When the command is run in the terminal there are no issues. Any Ideas what this could be? 

#### Variation 1
```ts
try {
  const {stdout} = await execa("heroku",["pg:backups:download", "-a", HEROKU_APP_NAME]);
} catch (error) {
  console.log(error);
}
```
#### Variation 2
```ts
const ps = await execa.command(`heroku pg:backups:download -a ${HEROKU_APP_NAME}`, {shell: true}).catch(async (err) =>  {
   console.log(err)
  })
```
### Error Output
```
{
  shortMessage: 'Command failed with exit code 1: heroku pg:backups:download -a TheNameGoesHere',
  command: 'heroku pg:backups:download -a TheNameGoesHere',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by ehmicky** [comment]
Hi @williamluke4,

Thanks for reporting this.

What does the following script show?

```js
const { promisify } = require('util')
const { execFile } = require('child_process')
const pExecFile = promisify(execFile)

const main = async function() {
  try {
    const {stdout} = await pExecFile("heroku",["pg:backups:download", "-a", HEROKU_APP_NAME]);
  } catch (error) {
    console.log(error);
  }
}

main()
```

Also, what is your OS, your Node.js version and your Execa version?

**Comment by williamluke4** [comment]
### Versions
**OS:**: Ubuntu 19.10
**Node**: 12.13.1
**Execa**: 4.0.0

### Output of Requested Script
```bash
Error: Command failed: heroku pg:backups:download -a TheNameGoesHere

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'heroku pg:backups:download -a TheNameGoesHere',
  stdout: '',
  stderr: ''
}
```

**Comment by ehmicky** [comment]
From the example above, you seem to get the same result when using `child_process` directly (instead of relying on Execa).

Based on this, I do not think this is an issue related to Execa, but to the specific `heroku` command that you are calling. There might be several reasons why the command works when entered manually in a terminal but not run programmatically (e.g. `stdin`, `stdout`, `stderr` might be handled differently, although this is probably not the problem here). 

Since this is not related to Execa, I think you might get a better response by asking on the Heroku CLI repository, and using the code sample above (the one using `child_process` instead of Execa)?

**Comment by williamluke4** [comment]
The Solution can be found [here](https://stackoverflow.com/questions/58468737/node-child-process-not-getting-the-output-from-cli/58475097#58475097)

Basically use [node-pty](https://github.com/microsoft/node-pty)

**Comment by ehmicky** [comment]
Thanks, glad you found a solution.

Did you try using the `stdio: 'inherit'` option with Execa?

**Comment by williamluke4** [comment]
`stdio: 'inherit'` Works

**Comment by williamluke4** [comment]
Thanks for your help :)

**Comment by ehmicky** [comment]
For additional information: when you launch a child process with Node.js (either through Execa or directly with `child_process`), `stdin`, `stdout` and `stderr` default to `pipe`. I.e. the standard streams are redirected to an internal variable instead of the terminal. By using `inherit` instead, they are redirected to/from the terminal, just like when you type in it.
