### ISSUE TITLE
Support `AbortController`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#449]
Node.js is adopting it for everything, so I think we should support it too.

https://developer.mozilla.org/en-US/docs/Web/API/AbortController

Node.js just added support for it in `.spawn()`: https://nodejs.org/en/blog/release/v15.5.0/

This would not replace the current `.cancel()` function, in the near-term at least.

**Comment by ehmicky** [comment]
The `signal` option was backported to Node `14.18.0`. Since Node 12 official support is a little less than 3 months, will we be getting this feature as part of dropping Node 12 support?

When using the `signal` option, the following could then probably be used:
  - `childProcess.cancel()` -> `AbortController.abort()`
  - `childProcess.isCanceled` and `error.isCanceled` -> `AbortSignal.aborted`.

Which would lead to the following action items:
  - Dropping Node 12 support
  - Documenting the `signal` option
  - Deprecating `childProcess.cancel()`, `childProcess.isCanceled` and `error.isCanceled`
  - Using `signal.aborted` to set the error message as "canceled" in [here](https://github.com/sindresorhus/execa/blob/e4b929547ade335b0dd9d7afe1a35989e19fbc8a/lib/error.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8)

What do you think?

**Comment by jopemachine** [comment]
> Dropping Node 12 support

Would it be not possible to just mark this API be available on Node 14.18.0 or higher version, and not dropping Node 12 support?
I think we could drop Node 12 though either because the current LTS is 16.

> Deprecating childProcess.cancel(), childProcess.isCanceled and error.isCanceled

I think it could feel a little awkward to have two APIs that work the same thing,
but in my humble opinion, I feel the existing API might be more human-friendly to users.
So, I'm not sure about this..

> Using signal.aborted to set the error message as "canceled" in [here](https://github.com/sindresorhus/execa/blob/e4b929547ade335b0dd9d7afe1a35989e19fbc8a/lib/error.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L8)

When `abort` is called, `cancel` is called in [here](https://github.com/sindresorhus/execa/pull/490/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R114), so I think the error message is set as "canceled" in the line.

**Comment by sindresorhus** [comment]
> What do you think?

👍
