### ISSUE TITLE
npm install not working with version 5.0

### ISSUE THREAD

**Issue by YizYah** [sindresorhus/execa#456]
Calling `npm install` will not execute properly for me with `execa` version 5.0.0 but works fine when I revert to v4.1.0:
```
  await execa('npm',
    ['install', '--prefix', '/tmp/foobar', '--save', 'barbells']);
```

I am not clear on why.  I'm using npm v14.9.0, running on Ubuntu 20.

**Comment by ehmicky** [comment]
Hi @YizYah,

Could you please include the output?
Also, could you please try either the following:
  - Using the `shell: true` Execa option
  - Using `child_process.spawn()` instead of `execa`

**Comment by SoldierAb** [comment]
> Hi @YizYah,
> 
> Could you please include the output?
> Also, could you please try either the following:
> 
> * Using the `shell: true` Execa option
> * Using `child_process.spawn()` instead of `execa`

I tried the parameter setting you mentioned, I encountered the same problem, and the result was no output.
I'm using node v16.4.0 , npm v7.18.1, running on mac os 10.15.7

**Comment by ehmicky** [comment]
Thanks for the additional information @SoldierAb 

If you still encountered the problem with `child_process.spawn()`, this means the problem is not specific to Execa but to Node.js core. If that's the case, I would suggest posting on either https://github.com/nodejs/node or https://github.com/npm/cli instead.
