### ISSUE TITLE
Change the way you indicate you want a Buffer

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#480]
Setting `{encoding: null}` is such a weird API I should never have inherited from `childProcess`.

We can introduce a new way while still supporting the old way.

Some possible solutions:

1. `{encoding: 'buffer'}` *(It's not technically an encoding, but who cares?)*
2. `{returnValue: 'string' | 'buffer'}`

In Got, we went with `{buffer: Boolean}`, but we already use that option name for something else.

**Comment by ehmicky** [comment]
I just found out that `{encoding: 'buffer'}` is actually supported by `child_process` and [documented](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback):

> If encoding is 'buffer', or an unrecognized character encoding, Buffer objects will be passed to the callback instead.

https://github.com/nodejs/node/blob/64a5c01b99e97854ae933d2210555ba6ee54db14/lib/internal/child_process.js#L1112

```js
> child_process.execSync('echo oh', {encoding: 'buffer'})
<Buffer 6f 68 0a>
```

Unrecognized character encoding behave the same, but only with `exec()` and `execFile()`. With `spawnSync()`, `execSync()` and `execFileSync()`, the following is thrown instead:

```
Uncaught TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: bufferr
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at Uint8Array.toString (node:buffer:851:11)
    at Object.spawnSync (node:internal/child_process:1116:43)
    at spawnSync (node:child_process:873:24)
    at Object.execSync (node:child_process:954:15)
```

`spawn()` does not have the `encoding` option, and ignores it.

Interestingly enough, the `'buffer'` encoding does not work with any `Buffer` method. For example, `Buffer.from(myString, 'buffer')` and `myBuffer.toString('buffer')` throw. The `null`/`'buffer'` encoding seems to be specific to `child_process`.

---

It turns out we accidentally supported `encoding: 'buffer'` and broke this with `8.0.0`. That's because the new `get-stream` version is not handling the `encoding` anymore, so we now use `myBuffer.toString(encoding)`, which throws with `'buffer'`.

We can easily fix this by turning:

https://github.com/sindresorhus/execa/blob/e7dee28c415fccfe2f06cf1794f8c84ecc549d46/lib/stream.js#L105

into:

```js
if (encoding === null || encoding === 'buffer') {
```

Then we would need to update the documentation. 
The types will require some changes as well since some generics depend on the `encoding` option.

https://github.com/sindresorhus/execa/blob/e7dee28c415fccfe2f06cf1794f8c84ecc549d46/index.d.ts#L15

I do think a boolean option like `binary` would be a better API. However, since this is the behavior of Node.js `child_process` itself, it seems to make sense to support it (especially since we accidentally used to support it).

What do you think?

**Comment by sindresorhus** [comment]
> I do think a boolean option like binary would be a better API. However, since {encoding: 'buffer'} is supported by Node.js child_process itself, it seems to make sense to use that instead.


Agreed. Although, I would prefer to remove support for `null` at some point.

**Comment by ehmicky** [comment]
Update: due to discussion #586, we are now considering removing `encoding: null`.
