### ISSUE TITLE
I want to show logs of command execution

### ISSUE THREAD

**Issue by MaybeQHL** [sindresorhus/execa#482]
like this : 
![image](https://user-images.githubusercontent.com/34638673/144371198-c9590957-d138-4c74-9ae5-c0032bf90a77.png)

code:
```
execa('npm run build'); //  I  get blank.
```

**Comment by ehmicky** [comment]
Hi @MaybeQHL,

Could you please describe your problem in more details?

One thing I can say from your code sample though: `execa('npm run build')` does not work since the file and its arguments are not a single string ([see the `README.md`](https://github.com/sindresorhus/execa#execafile-arguments-options)). Instead, you should use `execa.command('npm run build')` or `execa('npm', ['run', 'build'])`.
