### ISSUE TITLE
doesn't show child process spinner

### ISSUE THREAD

**Issue by tjx666** [sindresorhus/execa#526]
if I run `npx i18n pull --workspaces` in zsh, will show spinner:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/41773861/222268958-c20df2c1-95de-4529-9783-824b7daf0b36.png">

but using following code will not:

```typescript
export async function execWithOutput(command: string, cwd?: string) {
    const subprocess = execaCommand(command, {
        cwd,
        shell: true,
        stdin: 'inherit',
        env: { FORCE_COLOR: 'true' },
    });
    subprocess.stdout?.pipe(process.stdout);
    subprocess.stderr?.pipe(process.stderr);
    await subprocess;
    return subprocess;
}

execWithOutput('npx i18n pull --workspaces')
```

<img width="518" alt="image" src="https://user-images.githubusercontent.com/41773861/222269090-095ccdde-4901-4a4e-ab41-048fbd38ab89.png">

```
  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 381.21 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  npmPackages:
    execa: ^7.0.0 => 7.0.0 
```

**Comment by ehmicky** [comment]
Hi @tjx666,

Thanks for reaching out, but it seems like this issue might be more related to how process execution works in general, as opposed to Execa itself. 

In particular, this might be related to the TTY being non-interactive, due to using `pipe()` instead of `stdout: 'inherit'` or `stderr: 'inherit'`. Many spinner libraries are disabled by default when they detect that stdout or stderr is running in a not interactive TTY (such as in a CI).

However, this is not related to Execa itself, as you'd experience the same issue using `child_process.spawn()` directly.

Also, we would need a GitHub repository to reproduce this specific issue, since this involves a few implied dependencies and setup.
