### ISSUE TITLE
spawn ENOENT in GitHub Actions

### ISSUE THREAD

**Issue by timheerwagen** [sindresorhus/execa#544]
When i start a node package with npx in a github action, in which an execa command is executed, and then get the following error message directly when I try to start this command: `spawn turbo run build --scope=admin ENOENT` or `spawn npx turbo run build --scope=admin ENOENT`. On local everything works.

Apparently it cannot find the spawn command.

I have found the following workaround, which is to add {shell: true} to the execa command. But I don't like this for reasons that are obviously shown in the documentation.

```
shell

We recommend against using this option since it is:

- not cross-platform, encouraging shell-specific syntax.
- slower, because of the additional shell interpretation.
- unsafe, potentially allowing command injection.
```

**Comment by ehmicky** [comment]
Hi @timheerwagen,

If `turbo` is installed locally, you might be able to run it directly using the [`preferLocal: true` option](https://github.com/sindresorhus/execa#preferlocal). Without it, your local `node_modules` might be absent from the `PATH`, depending on the environment. You would also need to run it without using `npx`, since it would be unnecessary there and might interfere in the command spawning.

Can you try with that option enabled and without `npx`, and see whether his works?

**Comment by ehmicky** [comment]
This is a complex setup: GitHub action + turbo + Execa.
To be able to help any further, would you be able to create a reproduction repository? Thanks.

**Comment by ehmicky** [comment]
Thanks!
This code is calling `execa('npx turbo run build --scope=admin')`. The correct syntax is `execa('npx', ['turbo', 'run', 'build', '--scope=admin'])`. Link to [documentation](https://github.com/sindresorhus/execa#execafile-arguments-options) and [example](https://github.com/sindresorhus/execa#promise-interface).
