### ISSUE TITLE
Strange behaviour on quoted arguments

### ISSUE THREAD

**Issue by homersimpsons** [sindresorhus/execa#556]
**Note**: I do not know if this is expected, but I find the following behaviour rather strange

I would expect the following snippet to work:
```js
// index.mjs
import { $ } from 'execa'

await $`git commit --message "Initial commint"` // Intentional typo to ease understanding
```

But instead this trigger an error with the following message:
```
error: pathspec 'commint'' did not match any file(s) known to git
```

This is easily explainable because the escaped command look like:
```
git commit --message "\\"Initial" "commit\\""
```

- What is wrong with my understanding ?
- Am I supposed to use args for this case ?
```
await $`git ${['commit', '--message', 'Initial commint']}`
```
- Is there any more concise way ? Space escaping does not seem to work:
```
await $`git commit --message Initial\\ commint`
// escapedCommand: 'git commit --message "Initial\\" commit',
```

**Comment by ehmicky** [comment]
Hi @homersimpsons,

From the [documentation](https://github.com/sindresorhus/execa#command):

> Arguments are [automatically escaped](https://github.com/sindresorhus/execa#shell-syntax). They can contain any character, but spaces must use `${}` like $`echo ${'has space'}`.

The following:

```js
await $`git commit --message "Initial commint"`
```

Is interpreted as:

```js
await execa('git', ['commit', '--message', '"Initial', 'commint"')
```

Backlashes have no special meaning with `$`, so escaping with backslashes does not work. Using the following as you suggested does work:

```js
await $`git ${['commit', '--message', 'Initial commint']}`
```

However, a shorter way is this:

```js
await $`git commit --message ${'Initial commint'}`
```

Or:

```js
const message = 'Initial commint'
await $`git commit --message ${message}`
```

**Comment by homersimpsons** [comment]
Thank you I think I overlooked it a bit, I tried what was under [`execaCommand`](https://github.com/sindresorhus/execa#execacommandcommand-options) but it is different from the `$` template.

**Comment by taschetto** [comment]
@ehmicky how would you solve the following problem?

```ts
const railsCommand = 'console' // this comes from an argument and hold other values
await execaCommand(
  `aws ecs execute-command --cluster CLUSTER --task TASK --command "bash -c 'rails ${railsCommand}'" --interactive`
)
```

The generated command line seems well formed (`aws ecs execute-command --cluster CLUSTER --task TASK --command "bash -c 'rails console'" --interactive`) since I can paste it directly in my terminal and it works. Any tips?

```
Error: Command failed with exit code 252: aws ecs execute-command --cluster CLUSTER --task TASK --command "bash -c 'rails console'" --interactive

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

Unknown options: -c, console'", 'rails

    at makeError (file:///Users/taschetto/projects/npm-packages/packages/cli/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/taschetto/projects/npm-packages/packages/cli/node_modules/execa/index.js:124:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (file:///Users/taschetto/projects/npm-packages/packages/cli/src/commands/rails.ts:40:7) {
  shortMessage: `Command failed with exit code 252: aws ecs execute-command --cluster CLUSTER --task TASK --command "bash -c 'rails console'" --interactive`,
  command: `aws ecs execute-command --cluster CLUSTER --task TASK --command "bash -c 'rails console'" --interactive`,
  escapedCommand: `aws ecs execute-command --cluster a --task b --command "\\"bash" -c "'rails" "console'\\"" --interactive`
```

**Comment by ehmicky** [comment]
Hi @taschetto,

The first thing is: if you can use `$`, it is preferred over `execaCommand()`. `execaCommand()` is only meant when the full command + arguments are being supplied by the user, for example in a REPL. `$` is more secure and has better escaping features. It seems like, in your situation, you might not need `execaCommand()`.

In your situation, the following should work:

```js
await $`aws ecs execute-command --cluster CLUSTER --task TASK --command ${`bash -c 'rails ${railsCommand}'`} --interactive`
```

Internally, Execa re-interprets it as:

```js
await execa('aws', [
  'ecs', 
  'execute-command', 
  '--cluster', 
  'CLUSTER', 
  '--task', 
  'TASK', 
  '--command', 
  `bash -c 'rails ${railsCommand}'`, 
  '--interactive',
])
```

When `aws` receives `bash -c 'rails ${railsCommand}'` as argument, it runs it using its own process execution logic.

This would run Bash, which itself would run `rails ${railCommand}` with its own process execution logic.

So you have multiple layers there: Execa -> aws ecs -> Bash -> rails.

**Comment by taschetto** [comment]
@ehmicky worked like a charm! Thank you very much for the quick and perfect response. Looking forward to #891. I'm available if you need someone to help testing.

**Comment by ehmicky** [comment]
Thanks!

Unrelated, but the next release will also have support for multiline template strings, so you can do something like:

```js
await execa`aws ecs execute-command 
  --cluster CLUSTER 
  --task TASK 
  --command ${`bash -c 'rails ${railsCommand}'`} 
  --interactive`
```

**Comment by NMinhNguyen** [comment]
@ehmicky just wondering if `railsCommand` in the above example contained quotes/spaces, what would be the best way to escape it?

I have a use case where I’d like to run some commands via SSH, while injecting some environment variables, something like

```js
$`ssh some-host ${[
  'cd some/directory',
  'pnpm install',
  `PASSWORD={process.env.SOME_GITHUB_SECRET} some-command`,
].join('\n')}`
```

If the environment variable above contains any spaces/quotes, then it won’t be escaped. I wonder if `execa` could expose some of its internal escaping functions to support this use case? In this case if you know the variable only contains spaces, it’s easy enough to just wrap the variable in single quotes (not sure if that’s cross-platform though), but it’s impossible to guarantee with arbitrary values 😅

**Comment by ehmicky** [comment]
@NMinhNguyen Just to make it clear, any value passed to `${}` is kept as is. So when joining the array into a single string in the example above, you would be effectively passing a single argument. So this would be the same as doing:

```js
const singleArgument = `cd some/directory
pnpm install
PASSWORD=${process.env.SOME_GITHUB_SECRET} some-command`;

await $`ssh some-host ${singleArgument}`
```

Which is itself the same as doing the following:

```js
const singleArgument = `cd some/directory
pnpm install
PASSWORD=${process.env.SOME_GITHUB_SECRET} some-command`;

await execa('ssh', ['some-host', singleArgument]);
```

(I am assuming you actually meant `PASSWORD=${process.env.SOME_GITHUB_SECRET}` and not `PASSWORD={process.env.SOME_GITHUB_SECRET}`.)

So basically, you have several layers of execution: Execa -> SSH -> shell. Execa does its job at forward the argument as is to SSH. I believe SSH then forwards it to `/bin/sh` (I think?), which points to whatever is the system shell, for example Bash. 

So the problem here is not really with Execa's escaping, it is shell escaping.

Shells are not really cross-platform by nature. Windows can support most Unix shells with some manual setup, but not by default. So your main issue in terms of being cross-platform is the usage of a shell there. `PASSWORD=...` to set environment variables is a shell feature.

Since your command is already shell-specific (and not fully cross-platform), then the solution is your case would be to use shell-specific quoting. So the following might work for you?

```js
$`ssh some-host ${`cd some/directory
pnpm install
PASSWORD="${process.env.SOME_GITHUB_SECRET}" some-command`}`
```

**Comment by NMinhNguyen** [comment]
Thank you for the detailed explanation!

> I am assuming you actually meant

Yup, I did, sorry! Typed it up on my phone haha

I actually came across this `quoteString` function in the codebase, I suppose I could just borrow this particular line of code? https://github.com/sindresorhus/execa/blob/64d52dbb87a26da677b62f626fcd87e5bbe05cec/lib/arguments/escape.js#L65 But yeah, with your explanation it makes sense as to why `execa` probably doesn't need to export anything extra.

**Comment by ehmicky** [comment]
Yes, basically Execa is trying to stay away from any form of quoting. It just keeps arguments as is. So it purposely does not expose any quoting methods.

Usually, when confusion happens, it is not due to Execa, since Execa does not "touch" the arguments, but due to executing a program which itself interprets the command, such as `ssh`. Then that interpreter will most likely have its own escaping syntax, but that's unrelated to Execa.

In general, an easy solution is to remove the usage of a shell/interpeter. For example, instead of using a shell-specific syntax like `PASSWORD=... command`, using Execa's `env` option. Unfortunaly that's not that easy with remote execution, so might not be an option for you.

Then the next step would be to escape arguments manually using shell-specific quoting. The solution I gave above is actually only good to escape spaces. It would not escape sequences like `\n` or other double quotes. `$'...'` is better but require double escaping single quotes. If the input is untrusted, you should use a quoting library to prevent any shell injection.

**Comment by NMinhNguyen** [comment]
> If the input is untrusted, you should use a quoting library to prevent any shell injection.

Sorry for a stupid question, but is replacing all `'` with `'\''` not enough? Are there quoting libraries you'd recommend for this?

**Comment by ehmicky** [comment]
On most Unix shells, I think it should be enough, based [on the principle](https://www.gnu.org/software/bash/manual/html_node/Single-Quotes.html) that single quoting escapes everything but single quotes.
