### ISSUE TITLE
Add option to console.log command?

### ISSUE THREAD

**Issue by FreePhoenix888** [sindresorhus/execa#566]
# Code
```ts
import {execa} from 'execa';

const main = async () => {
  await execa('echo', ['word'], {stdio: 'inherit'});
};

main();
```
# Expected
```
> echo config
config
```
# Actual
```
config
```

**Comment by FreePhoenix888** [comment]
@aaronccasanova @sindresorhus @ehmicky

**Comment by ehmicky** [comment]
Hi @FreePhoenix888,

Could you please add more insights into your question? The behavior you are describing seems correct to me, so I might me misunderstanding what you mean.

In particular:
  - The prompt line `> echo config` is intentionally not output by Execa, since Execa runs commands programmatically, not in an interactive prompt
  - Your example should print `word`, not `config`. To print the argument, one would use `process.argv[2]`.

**Comment by ehmicky** [comment]
Because `stdout` is meant for the main output of a program (in this case, the child process's `stdout`), while `stderr` is meant for metadata, error information, etc. This includes information mostly related to CLI interactivity, such as prompt line, progress bar, etc.

**Comment by FreePhoenix888** [comment]
> Because `stdout` is meant for the main output of a program (in this case, the child process's `stdout`), while `stderr` is meant for metadata, error information, etc. This includes information mostly related to CLI interactivity, such as prompt line, progress bar, etc.
> 
> This allows users to print the command in verbose mode (both prompt line + output), while still retrieving its actual output (without the prompt line) programmatically.

I did not know that stderr is also meant for metadata. Thank you!
