### ISSUE TITLE
Some problems according to examples

### ISSUE THREAD

**Issue by amammad** [sindresorhus/execa#574]
I tried to learn new Node.js scripts functions so I faced two problems:
1. I think [pipeAll](https://github.com/sindresorhus/execa/blob/main/docs/scripts.md#piping-stdout-and-stderr-to-another-command) example should be ```await $({all: true})`echo example`.pipeAll($`cat`);```

2. ```await $`echo tmp`.pipeStdout($`cat`);``` have following error:
```
throw new TypeError('The target child process\'s stdin must be available.');
TypeError: The target child process's stdin must be available.
```
which If we use ```await $`echo tmp`.pipeStdout(execa('cat'));``` it will be OK.

**Comment by ehmicky** [comment]
Hi @amammad,

Thanks a lot for finding those errors!

For `pipeAll()`, `$({ all: true })` must indeed be used. It is actually documented [here](https://github.com/sindresorhus/execa#pipealltarget) but the example you mentioned is currently incorrect.

For `pipeStdout()`, the problem is that the `stdin` option defaults to `false` with `$` but `true` with `execa()`. While using `execa()` fixes this example, the better fix would be to use: 

```js
await $`echo tmp`.pipeStdout($({ stdin: 'pipe' })`cat`);
```

Multiple examples have this documentation error, all using ``$`cat` ``.

Would you be interested in submitting PRs to fix this?
