### ISSUE TITLE
`username` option in addition to `uid`?

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/execa#577]
Hi there - first of all thanks for this amazing package, it's great 🙌 

I saw that there is a `uid` option for running as a certain user, which is nice for running my shell script to set up and start PostgreSQL:

```tsx
const postgresUid = 70;
await execaCommand('bash ./scripts/alpine-postgresql-setup-and-start.sh', {
  cwd: projectPath,
  // postgres user, for initdb and pg_ctl
  uid: postgresUid,
  // Show output to simplify debugging
  stdout: 'inherit',
  stderr: 'inherit',
});
```

But this seems a bit brittle, that the `uid` will stay as `70` on this Docker container, over time. Would be great to have an option for `username` instead, to be able to pass in eg. `'postgres'`

**Comment by karlhorky** [comment]
## Workaround

A workaround is to dynamically get the `uid` via [`id -u <username>`](https://stackoverflow.com/a/39157691/1268612):

```tsx
const postgresUid = Number((await executeCommand('id -u postgres'))!);
await execaCommand('bash ./scripts/alpine-postgresql-setup-and-start.sh', {
  cwd: projectPath,
  // postgres user, for initdb and pg_ctl
  uid: postgresUid,
  // Show output to simplify debugging
  stdout: 'inherit',
  stderr: 'inherit',
});
```

**Comment by ehmicky** [comment]
Hi @karlhorky,

Generally speaking, relying on uid/gid is not cross-platform. In your case, this is not a problem since you're using a Docker image that has a known OS (Alpine). But I don't think we want to promote features that are known not to be cross-platform.

More specifically, Windows does not have the same concepts of uid/gid. Therefore, setting those options fails with Node.js when [spawning a new process](https://github.com/libuv/libuv/blob/dc1bb0088e8fbb92c81beb55341dcb7b4079717f/src/win/process.c#L973).

Based on this, I think that your workaround is the best solution if you know that you only need to support Linux.

As a side note, Node.js `os.userInfo().username` does very similar syscalls than coreutils `id`, basically reading/parsing `/etc/passwd`, but without having a spawn a new process. Unfortunately, it always use the current euid, instead of letting you specify an arbitrary username (like `postgres`). `libuv` does have a function that [does exactly this](https://github.com/libuv/libuv/blob/dc1bb0088e8fbb92c81beb55341dcb7b4079717f/src/unix/core.c#L1363C5-L1363C22) which was added 9 months ago by [the following PR](https://github.com/libuv/libuv/pull/3523), but it looks like it is not used nor exposed by Node.js.

**Comment by karlhorky** [comment]
Ok thanks for the quick answer, understood! Closing this issue.

I guess we can leave this in this closed issue as a "recipe" for others.
