### ISSUE TITLE
Sync methods

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/execa#7]
`execa` already cover the async methods and the sync methods could then take advantage of of the npm path thing, and `utf8` by default instead of `buffer`.

**Comment by jamestalmage** [comment]
I looked into this. There is no good way to support Node `0.10` (which you don't anyways).

See https://github.com/IndigoUnited/node-cross-spawn/issues/28

**Comment by sindresorhus** [comment]
@jamestalmage I'm aware, but this only supports >=0.12.

Btw, did you need this for anything? I just implemented `execa.sync()`.

I could also use some feedback on the open issues if you're interested.

**Comment by jamestalmage** [comment]
`is-git-clean` uses this, but implements it's own sync call. That can be updated now.

I think this can be closed.

**Comment by sindresorhus** [comment]
I didn't implement `.spawnSync` and `.execSync`, but can easily be added if there is a need. I've personally never needed those.

**Comment by lukeed** [comment]
AFAIK, `.spawnSync` and `.execSync` are the only two functions keeping Execa from supporting 0.10. 

I'm not 100% certain, but it may be worth it to attach a ponyfill for global LTS coverage.

**Comment by mgol** [comment]
> I'm not 100% certain, but it may be worth it to attach a ponyfill for global LTS coverage.

Any polyfill for those on Node 0.10 (unless ones that starve the event loop by hacks killing the CPU) will require native dependencies so would increase the burden on everyone since you can't specify a dep should only be installed for a specific Node version. That's not worth it.

**Comment by sindresorhus** [comment]
Node.js 0.10 is out of LTS. We're not going to do anything to support it.

**Comment by lukeed** [comment]
@mgol Couldn't you just do something like:

```js
var child = require('child_process');
// ...
child.spawnSync = child.spawnSync || require('runsync').spawn;
```

**Comment by lukeed** [comment]
Ok 👍 Reason enough.

**Comment by mgol** [comment]
@lukeed No because you then need to add `runsync` to package.json and every user will download it. If they don't have the correct setup for installing native deps (on Windows it's not that easy, you need Visual Studio etc.) it will break or at least display errors to the console when installing if you add it as an optional dependency.

@sindresorhus Node 0.10 is not out of LTS but out of the LTS active phase, it's in the LTS maintenance phase. BTW, Node 0.12 has been in the LTS maintenance mode since the beginning of April so its support status is currently identical to Node 0.10. Not that it affects what I think about supporting Node 0.10 here (not worth it IMO) but if you want to support only up to LTS maintenance phase, you can drop Node 0.12 as well.

**Comment by mgol** [comment]
More info about Node LTS is at https://github.com/nodejs/LTS, the graphic at the bottom explains it pretty well.
