### ISSUE TITLE
--inspect-brk can break execaNode ipc communication

### ISSUE THREAD

**Issue by otakustay** [sindresorhus/execa#766]
If I have a `main.mjs` like:

```js
import {execaNode} from 'execa';

const child = execaNode('child.mjs', {nodeOptions: ['--inspect-brk=9988']});
child.stdout.pipe(process.stdout);
child.send({message: 'Hello'});
```

While my `child.mjs` is a simple message logging:

```js
process.on(
    'message',
    data => console.log(data)
);
```

When I execute `main.mjs`, I can't see `{message: 'Hello'}` printed in console, however after removing `nodeOptions` argument everything goes fine, other `nodeOptions` like `--disable-proto` works find with ipc.

I did some search but have no luck, now I'm wondering if this is a restriction on node itself or something `execa` can fix.

**Comment by ehmicky** [comment]
Hi @otakustay,

Thanks for reaching out. This behavior is not Execa specific: it is the same with `child_process.spawn()`.
Also, it is unrelated to using an `ipc` channel.

The `--inspect-brk` flag's intent is to put a `debugger` statement at the beginning of the script, i.e. to stop it as it starts. As a consequence, when `child.mjs` starts, it stops, waiting for you to start a debugging client and click on "continue".

You can experience this by using the following example.

```js
// main.mjs
import {spawn} from 'node:child_process';

const child = spawn('node', ['--inspect-brk=9988', 'child.mjs'], {stdio: ['pipe', 'inherit', 'inherit', 'ipc']})
child.send({message: 'Hello'});
```

```js
// child.mjs
console.log('This is not printed')
process.on('message', data => console.log(data));
```

```sh
$ node main.mjs
Debugger listening on ws://127.0.0.1:9988/45bfb978-585d-41ee-993f-0bfe046bb37a
For help, see: https://nodejs.org/en/docs/inspector
```

`child.mjs` does not print `"This is not printed"` even though its `stdout` is `inherit`.
It prints the debugger message since its `stderr` is `inherit`.
It does not execute `process.on('message')` since it is in stopped state. Therefore, `child.send()` does not do anything.
