### ISSUE TITLE
piping not work

### ISSUE THREAD

**Issue by sklme** [sindresorhus/execa#932]
version 8.0.1

I try this
```ts
await $`npm run build`.pipe`sort`.pipe`head -n2`;
```
but not work.

ts give me a error:
<img width="926" alt="image" src="https://github.com/sindresorhus/execa/assets/4933537/a7b6c594-b745-4f2d-9dc9-97ddeef5968f">

**Comment by ehmicky** [comment]
Hi @sklme,

The `.pipe()` method has not been released yet. It should be released in a few weeks.

In the meantime, you can see the `8.0.1` documentation [here](https://github.com/sindresorhus/execa/tree/v8.0.1).

**Comment by sklme** [comment]
@ehmicky 

Thanks for reply.
So how to use the pipe symbol in version 8.0?

I try
```ts
await $`git diff --cached ${filePath} | grep '^+[^+]'`
```

give me en error:
<img width="694" alt="image" src="https://github.com/sindresorhus/execa/assets/4933537/3de053cf-d684-41ec-9c49-a3241e11f251">

and with `--`symbol：
```ts
await $`git diff --cached --  ${filePath} | grep '^+[^+]'`
```
Found that `grep` did not take effect, stdout is:
<img width="513" alt="image" src="https://github.com/sindresorhus/execa/assets/4933537/8e1e274a-9c19-4f3e-847c-b9d32108d489">

Only lines start with + should be retained.

**Comment by ehmicky** [comment]
Hi @sklme,

`|` is a [shell-specific symbol](https://github.com/sindresorhus/execa?tab=readme-ov-file#shell-syntax).

> No shell interpreter (Bash, cmd.exe, etc.) is used unless the [shell option](https://github.com/sindresorhus/execa?tab=readme-ov-file#shell) is set. This means shell-specific characters and expressions ($variable, &&, ||, ;, |, etc.) have no special meaning and do not need to be escaped.

You can use a shell by using the [`{shell: true}` option](https://github.com/sindresorhus/execa?tab=readme-ov-file#shell).

The `subprocess.pipe()` method is better than using `{shell: true}` + the pipe symbol because it:
  - Is more cross-platform (Windows `cmd.exe` does not have `|`)
  - Is faster (no shell is spawned)
  - Is safer (no possible shell injection)
  - Can easily pipe from `stderr`, `stdout` + `stderr`, or other file descriptor
  - Can pipe to other file descriptors than `stdin`
  - Can be abort with the `abortSignal` option
  - Has better error handling behavior
  - The result of each command is available as `result.pipedFrom`, instead of only the last one
  - And some additional smaller details

This will be released soon, please keep an eye! :)

**Comment by ehmicky** [comment]
Execa 9.0.0 has now been released. Please see (and share!) the [release post](https://medium.com/@ehmicky/execa-9-release-d0d5daaa097f) and the [changelog](https://github.com/sindresorhus/execa/releases/tag/v9.0.0).

That release includes `subprocess.pipe()`.
